### ISSUE TITLE
Types in types.js seem to be missing from API function returns?

### ISSUE THREAD

**Issue by wu-lee** [explodingcamera/subsonic-api#8]
Thanks for this library.

I'm using it to create a Navidrome client in SvelteKit which can access the Jukebox, since this is a feature I want that Navidrome doesn't seem to offer.  A personal itch to scratch, and a chance to try SvelteKit.

## Expected

Case in point: the [`jukeboxControl` ] method.

What I'd expect is for this to return a `JukeboxStatus` value, as I see is already defined in the library [here]. Or possibly a `JukeboxPlaylist` if the `action` parameter is `"get"`.

## Actual behaviour

This value *does* seems to be returned - but the return type of the method is defined to be a `BaseSubsonicStatus` - so none of the information is present so far as Typescript knows, making it a bit inconvenient to use.

Furthermore, looking at the other API  methods, this seems to be a common situation, if not universal.

## Question

Is this intentional? If so, what's the intended way to access these types?

If not, what's the best way to rectify this?

Thanks!

[`jukeboxControl`]: https://www.subsonic.org/pages/api.jsp#jukeboxControl
[here]: https://github.com/explodingcamera/subsonic-api/blob/7ae0427926d4f6eeeaf82945b2b776f0274bd42c/src/types.ts#L208

**Comment by explodingcamera** [comment]
Hi, most endpoints return just an empty response (success / error), but I found this and a few other minor issues with the types in some methods, which should now be fixed in the latest version (I only use a couple of the methods myself). I've also added tests for the most common operations. Most of the types were initially generated from the Subsonic XML schemas, which had some problems.

If anything else seems off, feel free to open an issue or PR. Thanks!
